services:

  postgres:
    image: postgres:17
    container_name: postgres_bookstation
    environment:
      POSTGRES_DB: bookstation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - book-station-network

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: book-station-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstation_db
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: 1234
#      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
#      SPRING_FLYWAY_ENABLED: "true"
#      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
#      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
#      SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
#    depends_on:
#      - postgres
#    networks:
#      - book-station-network
#
#  frontend:
#    build:
#      context: ./frontend/frontend-app
#      dockerfile: Dockerfile
#    container_name: book-station-frontend
#    ports:
#      - "4200:80"
#    depends_on:
#      - backend
#    networks:
#      - book-station-network

volumes:
  postgres_data:
#
#networks:
#  book-manager-network:
#    driver: bridge